extends Node
## res://autoload/Sfx.gd — autoload "Sfx"
##
## Plays the game's sounds and the ambient music loop. Sounds are local to
## each peer: gameplay code decides *when* (usually on a host-driven sync or
## RPC, so every peer hears the same thing), this just plays them.
## Sounds live in assets/audio/ (generated by tools/gen_audio.py); replace a
## WAV with a recording of the same name to change it.

const SOUNDS := {
	"pickup": preload("res://assets/audio/pickup.wav"),
	"release": preload("res://assets/audio/release.wav"),
	"place_correct": preload("res://assets/audio/place_correct.wav"),
	"place_wrong": preload("res://assets/audio/place_wrong.wav"),
	"toss": preload("res://assets/audio/toss.wav"),
	"ping": preload("res://assets/audio/ping.wav"),
	"click": preload("res://assets/audio/click.wav"),
	"category_complete": preload("res://assets/audio/category_complete.wav"),
	"round_complete": preload("res://assets/audio/round_complete.wav"),
}
const MUSIC := preload("res://assets/audio/music_loop.wav")
const MUSIC_DB := -15.0
const MAX_VOICES := 24   # never let a burst of events pile up sounds

var music_player: AudioStreamPlayer
var music_enabled := true


func _ready() -> void:
	process_mode = Node.PROCESS_MODE_ALWAYS
	get_tree().auto_accept_quit = false  # see _notification
	music_player = AudioStreamPlayer.new()
	var loop := MUSIC.duplicate() as AudioStreamWAV
	loop.loop_mode = AudioStreamWAV.LOOP_FORWARD
	loop.loop_begin = 0
	loop.loop_end = int(round(loop.get_length() * loop.mix_rate))
	music_player.stream = loop
	music_player.volume_db = MUSIC_DB
	add_child(music_player)
	music_player.play()


## Closing the window mid-sound would otherwise leave playbacks registered
## with the audio server as it shuts down ("ObjectDB instances leaked at
## exit"). So we take over the close: stop every sound, give the audio
## server a moment to let go of them, then quit.
func _notification(what: int) -> void:
	if what == NOTIFICATION_WM_CLOSE_REQUEST:
		quit_cleanly()


func quit_cleanly() -> void:
	stop_all()
	await get_tree().create_timer(0.15).timeout
	get_tree().quit()


func stop_all() -> void:
	for c in get_children():
		if c is AudioStreamPlayer or c is AudioStreamPlayer3D:
			c.stop()
			c.stream = null


func _unhandled_input(event: InputEvent) -> void:
	if event.is_action_pressed("toggle_music"):
		toggle_music()


func toggle_music() -> void:
	music_enabled = not music_enabled
	var tw := create_tween()
	tw.tween_property(music_player, "volume_db", MUSIC_DB if music_enabled else -60.0, 0.6)


## Plays `sound`. With a position it's a 3D sound (quieter with distance),
## without one it's a flat UI-style sound. A little random pitch keeps
## repeated sounds from feeling mechanical.
func play(sound: String, pos: Variant = null, volume_db := 0.0, pitch_jitter := 0.06) -> void:
	if not SOUNDS.has(sound) or get_child_count() > MAX_VOICES:
		return
	var p: Node
	if pos is Vector3:
		var p3 := AudioStreamPlayer3D.new()
		p3.unit_size = 6.0
		p3.max_distance = 45.0
		p3.attenuation_model = AudioStreamPlayer3D.ATTENUATION_INVERSE_DISTANCE
		p3.stream = SOUNDS[sound]
		p3.volume_db = volume_db
		p3.pitch_scale = 1.0 + randf_range(-pitch_jitter, pitch_jitter)
		add_child(p3)
		p3.global_position = pos
		p3.play()
		p3.finished.connect(p3.queue_free)
		p = p3
	else:
		var p2 := AudioStreamPlayer.new()
		p2.stream = SOUNDS[sound]
		p2.volume_db = volume_db
		p2.pitch_scale = 1.0 + randf_range(-pitch_jitter, pitch_jitter)
		add_child(p2)
		p2.play()
		p2.finished.connect(p2.queue_free)
		p = p2
	# Safety net: free even if `finished` never fires (e.g. no audio
	# device). Captures the id, not the node — the node has usually freed
	# itself by then, and capturing a freed object logs an engine error.
	var id := p.get_instance_id()
	get_tree().create_timer(SOUNDS[sound].get_length() + 0.5).timeout.connect(
		func():
			var o := instance_from_id(id)
			if o: o.queue_free())


## Gives every Button under `root` a soft click.
func wire_buttons(root: Node) -> void:
	for b in root.find_children("*", "Button", true, false):
		if not b.pressed.is_connected(_on_button_pressed):
			b.pressed.connect(_on_button_pressed)


func _on_button_pressed() -> void:
	play("click")
